baseURL = "https://ktdevx.github.io/hugo-theme-veryl/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Veryl"
theme = "hugo-theme-veryl"
enableRobotsTXT = true
[pagination]
  pagerSize = 10

[params]
  description = "分かりやすく、目的に集中できるWebサイトを構築するためのHugoテーマです。"
  mainSections = ["posts"]
